#!/bin/bash

# The directory of the dotfiles repository.
dir="$( cd "$( dirname "${BASH_SOURCE:-$0}" )" && pwd )"

# Create a symlink from a file to a destination, moving any existing file to
# /tmp.
# Arguments:
#   - $1 file name
#   - $2 from path
#   - $3 destination path
symlink() {
  if [ -L $3 ]; then
    rm $3 # If its a link, remove it
  elif [ -f $3 ]; then
    tmp=$(mktemp "/tmp/${1}.XXX")
    echo "$3 exists already! moving to ${tmp}"
    mv $3 "${tmp}"
  fi

  ln -s $2 $3
}

for file in gitconfig gitignore hushlogin tmux.conf vimrc ideavimrc
do
  symlink "${file}" "${dir}/${file}" "${HOME}/.${file}"
done

# Install ctags file from local rust repo.
if [ ! -e "${HOME}/stc/rust/rust/src/etc/ctags.rust" ]; then
  symlink "ctags.rust" "${HOME}/src/rust/rust/src/etc/ctags.rust" "${HOME}/.ctags"
fi

# Install vim plugins, if vim exists.
if [[ $(type -P vim) ]]; then

  if [ ! -e "${HOME}/.vim/autoload/plug.vim" ]; then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
          https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  fi

  vim +PlugUpdate +qall
fi

# Install oh-my-fish and config, if fish exists.
if [[ $(type -P fish) ]]; then

  if [ ! -e "${HOME}/opt/oh-my-fish" ]; then
    mkdir -p $HOME/opt
    git clone git://github.com/oh-my-fish/oh-my-fish.git "${HOME}/opt/oh-my-fish"
    cp "${HOME}/opt/oh-my-fish/templates/config.fish" "${HOME}/.config/fish/config.fish"
  fi

  symlink "config.fish" "${dir}/config.fish" "${HOME}/.config/fish/config.fish"
else
  echo "fish shell not installed; skipping oh-my-fish and fish configuration"
fi
