#!/bin/bash

set -e

# The directory of the dotfiles repository.
dir="$( cd "$( dirname "${BASH_SOURCE:-$0}" )" && pwd )"

# Create a symlink from a file to a destination, moving any existing file to
# /tmp.
# Arguments:
#   - $1 file name
#   - $2 from path
#   - $3 destination path
symlink() {
  if [ -L $3 ]; then
    rm $3 # If its a link, remove it
  elif [ -f $3 ]; then
    tmp=$(mktemp "/tmp/${1}.XXX")
    echo "$3 exists already! moving to ${tmp}"
    mv $3 "${tmp}"
  fi

  ln -s $2 $3
}

for file in gitconfig gitignore hushlogin tmux.conf vimrc ideavimrc
do
  symlink "${file}" "${dir}/${file}" "${HOME}/.${file}"
done

# Install config.fish.
symlink config.fish "${dir}/config.fish" "${HOME}/.config/fish/config.fish"

# Install vim plugins, if vim exists.
if [[ $(type -P vim) ]]; then

  if [ ! -e "${HOME}/.vim/autoload/plug.vim" ]; then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
          https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  fi

  vim +PlugUpdate +qall
fi
