format = """
$all\
$fill\
$time\
$line_break\
$character
"""

[fill]
symbol = " "

[time]
disabled = false
style = "bold bright-black"
format = "[$time]($style)"

[directory]
truncation_symbol = "…/"

[aws]
disabled = true

[gcloud]
disabled = true

[nodejs]
disabled = true

[buf]
disabled = true

[git_status]
disabled = true
